version: '3.8'

services:
  ocr-service:
    image: jackipro1509/ocr-service:latest
    container_name: ocr-service
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/temp_uploads
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 